/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Praktikum_2 extends javax.swing.JFrame {
    String jns =" ";
    int jml;

    
    public Praktikum_2() {
        initComponents();
        getJumlah();
        setJenis();
        jPanel2.setVisible(false);
        pilihanbil.setEnabled(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bil4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        b4 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        thasil = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();
        Jenis = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Program Aritmatika");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 70, 130, 15);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Program Aritmatika");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 10, 210, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(null);

        bil4.setText("Bilangan 4");
        jPanel2.add(bil4);
        bil4.setBounds(40, 220, 110, 14);

        jLabel4.setText("Jumlah Bilangan");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 60, 110, 14);

        bil1.setText("Bilangan 1");
        jPanel2.add(bil1);
        bil1.setBounds(40, 100, 110, 14);

        bil2.setText("Bilangan 2");
        jPanel2.add(bil2);
        bil2.setBounds(40, 140, 110, 14);

        bil3.setText("Bilangan 3");
        jPanel2.add(bil3);
        bil3.setBounds(40, 180, 110, 14);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        jPanel2.add(pilihanbil);
        pilihanbil.setBounds(170, 50, 130, 30);

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel2.add(b4);
        b4.setBounds(170, 220, 130, 30);
        jPanel2.add(b1);
        b1.setBounds(170, 100, 130, 30);

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel2.add(b2);
        b2.setBounds(170, 140, 130, 30);

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel2.add(b3);
        b3.setBounds(170, 180, 130, 30);

        jButton1.setText("hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(170, 260, 63, 23);

        thasil.setEditable(false);
        jPanel2.add(thasil);
        thasil.setBounds(170, 290, 130, 50);

        ket.setBackground(new java.awt.Color(255, 102, 0));
        ket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ket.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ket);
        ket.setBounds(100, 20, 160, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 100, 320, 350);

        Jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        Jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisActionPerformed(evt);
            }
        });
        jPanel1.add(Jenis);
        Jenis.setBounds(200, 60, 160, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 470);

        setBounds(0, 0, 416, 508);
    }// </editor-fold>//GEN-END:initComponents

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        
        
        if (jns.equals("Penjumlahan")) {
            if (jml == 2) {
                hsl = a1 + a2;
                thasil.setText(""+a1 +" + "+ a2 +" = "+ hsl);
            }
             if (jml == 3) {
                 a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 + a2 + a3;
                thasil.setText(""+ a1 +" + "+ a2 +" + " + a3 + " = "+ hsl);
            }
              if (jml == 4) {
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+ a1 +" + "+ a2+" + "+ a3 + " + " + a4 + " = "+ hsl);
            }
              
            
        }
        else if (jns.equals("Pengurangan")){
            if (jml == 2) {
                hsl = a1 - a2;
                thasil.setText(""+a1+" - "+a2+" = "+hsl);
            }
            if (jml == 3) {
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 - a2 - a3;
                thasil.setText(""+a1+" - "+a2+" - "+ a3+" = "+hsl);
            }
             if (jml ==4) {
                 a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                thasil.setText(""+a1+" - "+a2+" - "+ a3+" - "+a4+" = "+hsl);
            }
        }
        else if (jns.equals("Perkalian")) {
               if (jml == 2) {
                hsl = a1 * a2;
                thasil.setText(""+a1+" X "+a2+" = "+hsl);
            }
            if (jml == 3) {
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 * a2 * a3;
                thasil.setText(""+a1+" X "+a2+" X "+ a3+" = "+hsl);
            }
             if (jml == 4) {
                 a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                thasil.setText(""+a1+" X "+a2+" X "+ a3+" X "+a4+" = "+hsl);
            }
        }
        else if (jns.equals("Pembagian")) {
               if (jml == 2) {
                hsl = a1 / a2;
                thasil.setText(""+a1+" : "+a2+" = "+hsl);
            }
            if (jml == 3) {
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 / a2 / a3;
                thasil.setText(""+a1+" : "+a2+" : "+ a3+" = "+hsl);
            }
             if (jml ==4) {
                 a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                thasil.setText(""+a1+" : "+a2+" : "+ a3+" : "+a4+" = "+hsl);
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void JenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisActionPerformed
        setJenis();
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        getJumlah();        // TODO add your handling code here:
    }//GEN-LAST:event_pilihanbilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktikum_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jenis;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel ket;
    private javax.swing.JComboBox<String> pilihanbil;
    private javax.swing.JTextField thasil;
    // End of variables declaration//GEN-END:variables

    private void setJenis() {
        if (Jenis.getSelectedItem().equals("Penjumlahan")) {
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            jPanel2.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if (Jenis.getSelectedItem().equals("Pengurangan")) {
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            jPanel2.setVisible(true);
            pilihanbil.setEnabled(true);
        }
         else if (Jenis.getSelectedItem().equals("Perkalian")) {
            jns = "Perkaliann";
            ket.setText("Perkalian");
            jPanel2.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if (Jenis.getSelectedItem().equals("Pembagian")) {
            jns = "Pembagian";
            ket.setText("Pembagian");
            jPanel2.setVisible(true);
            pilihanbil.setEnabled(true);
        }
    }

    private void getJumlah() {
        if (pilihanbil.getSelectedItem().equals("2")){ 
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true); 
        jml=2;
        
      } else if (pilihanbil.getSelectedItem().equals("3")){ 
        bil3.setVisible(true);
        bil4.setVisible(false);
        b3.setVisible(true);
        b4.setVisible(false);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true); 
        jml=3;
    }
        else if (pilihanbil.getSelectedItem().equals("4")){ 
        bil3.setVisible(true);
        bil4.setVisible(true);
        b3.setVisible(true);
        b4.setVisible(true);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true); 
        jml=4;
    }
  }
}
